### ISSUE TITLE
Exposing environment vars

### ISSUE THREAD

**Issue by njordhov** [adzerk-oss/env#1]
The `env` macro can potentially be harmful when used with clojurescript, by making it easy to mistakenly expose supposedly secret environment vars to the world.

Simply using `(env)` in code ~~can~~ _will typically_ result in **all environment vars** being embedded in the compiled javascript served to the browser. This may include vars supposed to be kept confidential such as secret keys.

However, it is useful to be able to embed environment vars during cljs compile time, particularly for browser apps. I suggest changing the `env` macro to require the name of an environment var as argument, and make sure to only inline the value of the specified var in compiled code.

**Comment by micha** [comment]
That's an excellent point, thanks! I think simply warning the user about this when they use `env/env` in cljs (at compile time) would be sufficient, no? It's a useful macro to have sometimes.

**Comment by njordhov** [comment]
The 'env' macro **negates the security benefits of twelve-factor app use of config vars.** Even if there is a warning that using 'env' introduces **severe risk of exposing secret environment vars to the world**, there is still the issue that third party projects depending on a library using 'env' may end up inadvertently making secret environment vars public.

**Comment by jashmenn** [comment]
@TerjeNorderhaug Agreed. Unfortunately, this is a serious flaw in an otherwise great library.

**Comment by micha** [comment]
@TerjeNorderhaug I think you're right again. Thanks!
