### ISSUE TITLE
Unexpected def behavior

### ISSUE THREAD

**Issue by arichiardi** [adzerk-oss/env#2]
There might be some problem either in the README or in the code or in my understanding :dancer: 

I have `(env/def SOME_VAR "test)` in my `build.boot` but (`System.getenv "SOME_VAR")` always returns `nil` in the repl. Instead, `(System/getProperty "SOME_VAR")` returns "test".

So system prop are defined instead of environment vars but the README states:

> the system property of the same name if it is set, or`

...and in my case no property with name `SOME_VAR` is not set...

It is not a big deal, but some tool (`cprop`) expects different syntax form System properties vs Env vars so it would be cool to address the problem (if any).

Thanks for this very nice tool again!

**Comment by daveyarwood** [comment]
Yeah, it definitely looks like it's setting properties, not env vars: https://github.com/adzerk-oss/env/blob/master/src/adzerk/env.clj

It looks like this library overrides JVM system properties, not environment variables, and when it reads a value, it looks first in the system properties, then the environment variables. I'm not sure whether or not this (the fact that it doesn't affect `(System/getenv "MY_VAR")` after setting `MY_VAR` to some value via `env/def`) is problematic.

**Comment by arichiardi** [comment]
Yes I saw that too and it is probably a consistent implementation choice, but then the README does not read right...

**Comment by daveyarwood** [comment]
Which part? If you make a PR, I'll be happy to weigh in :)

**Comment by arichiardi** [comment]
I can do it too, what do you think about:

The values are set to:
- the system property of the same name <s>if it is set<s>, or

<s>\- the environment variable of the same name otherwise</s>

From what I can see it never sets environment variables

**Comment by daveyarwood** [comment]
I think the confusing part is actually the first part, "The values are set to:"

I think the intended meaning was, "The values are _read from_:" (the system property if set, otherwise the env var)

You can see in the "Set" section below that, that it updates the system property and the Clojure var.

**Comment by arichiardi** [comment]
True that
